
volumes:
  pg_data:
  static:
  media:

services:
  redis:
    image: "redis:6.2-alpine"
    environment:
      - TZ=Europe/Minsk
  ovaynisedb:
    image: postgres:14.5
    env_file: .env
    volumes:
      - ${MEDIA_ROOT_LOCAL}/db:/var/lib/postgresql/data
  xtred:
    build: ./xtred/
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST_DOCKER}
      - TZ=Europe/Minsk
    volumes:
      - static:/backend_static
      - media:${MEDIA_ROOT_LOCAL}
    depends_on:
      - ovaynisedb
  ovbot:
    build: ./ovbot/
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST_DOCKER}
      - BEARER_TOKEN=${BEARER_TOKEN_LOCAL}
      - URL_SERVER=${URL_SERVER_LOCAL}
      - TZ=Europe/Minsk
    volumes:
      - media:${MEDIA_ROOT_LOCAL}
    depends_on:
      - ovaynisedb
  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
      - media:${MEDIA_ROOT_LOCAL}
    ports:
      - 8000:80
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST_DOCKER}
      - TZ=Europe/Minsk
  celery:
    build: ./xtred/
    command: celery -A xtred worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - ovaynisedb
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST_DOCKER}
    volumes:
      - static:/backend_static
      - media:${MEDIA_ROOT_LOCAL}

  celery-beat:
    build: ./xtred/
    command: celery -A xtred beat --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - ovaynisedb
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST_DOCKER}
    volumes:
      - static:/backend_static
      - media:${MEDIA_ROOT_LOCAL}