version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  ovaynisedb:
    image: postgres:14.5
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  xtred:
    image: ovaynise/engineer_xtred
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/home/ovaynise/engineer/media/
  ovbot:
    image: ovaynise/engineer_ovbot
    env_file: .env
    depends_on:
      - ovaynisedb
  gateway:
    image: ovaynise/engineer_gateway
    volumes:
      - static:/staticfiles/
      - media:/home/ovaynise/engineer/media/
    ports:
      - 8000:80