version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  ovaynisedb:
    image: postgres:14.5
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  xtred:
    image: ${DOCKER_USERNAME}/engineer_xtred
    env_file: .env
    volumes:
      - static:/backend_static
      - media:${MEDIA_ROOT}
  ovbot:
    image: ${DOCKER_USERNAME}/engineer_ovbot
    env_file: .env
    depends_on:
      - ovaynisedb
  gateway:
    image: ${DOCKER_USERNAME}/engineer_gateway
    volumes:
      - static:/staticfiles/
      - media:${MEDIA_ROOT}
    ports:
      - 8000:80
