version: '3'

volumes:
  pg_data:
  static:


services:
  ovaynisedb:
    image: postgres:14.5
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  xtred:
    build: ./xtred/
    env_file: .env
    volumes:
      - static:/backend_static
  ovbot:
    build: ./ovbot/
    env_file: .env
    depends_on:
      - ovaynisedb
  gateway:
    build: ./gateway/
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80