FROM python:3.9

WORKDIR /app

COPY requirements.txt ./
RUN pip install --upgrade setuptools pip
RUN pip install -r requirements.txt

COPY . /app

CMD ["python", "xtred/manage.py", "runserver", "0.0.0.0:8000"]