version: '3.7'

services:
  engineersite:
    container_name: engineer-site
    build:
      context: .
    image: engineer-site-image
    env_file:
      - ./.env
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    entrypoint: >
      sh -c "
      python xtred/manage.py makemigrations &&
      python xtred/manage.py migrate &&
      python xtred/manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL ||
      true &&
      python xtred/manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    networks:
      - ${DJANGO_NETWORK}

networks:
  ovaynisenetwork:
    external: true
