# Generated by Django 4.2.14 on 2024-08-25 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("constructions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AddField(
            model_name="constructionsworks",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AddField(
            model_name="constructionsworks",
            name="constructions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constructions_worksed",
                to="constructions.constructions",
            ),
        ),
        migrations.AddField(
            model_name="constructionsworks",
            name="constructions_company",
            field=models.ManyToManyField(
                blank=True,
                related_name="constructions_worksed_company",
                to="constructions.constructionscompany",
            ),
        ),
        migrations.AddField(
            model_name="constructionscompany",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AddField(
            model_name="constructionscompany",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity",
                to="constructions.entity",
                verbose_name="Юр.лицо по договору",
            ),
        ),
        migrations.AddField(
            model_name="constructionscompany",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_company",
                to="constructions.location",
                verbose_name="Основной регион подрядчика",
            ),
        ),
        migrations.AddField(
            model_name="constructions",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AddField(
            model_name="constructions",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="constructions.brandtype",
                verbose_name="Брэнд АЗС",
            ),
        ),
        migrations.AddField(
            model_name="constructions",
            name="constructions_company",
            field=models.ManyToManyField(
                blank=True,
                related_name="constructions_company",
                to="constructions.constructionscompany",
                verbose_name="Подрядчик",
            ),
        ),
        migrations.AddField(
            model_name="constructions",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="constructions.location",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="constructions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="constructions.constructions",
            ),
        ),
        migrations.AddField(
            model_name="brandtype",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
    ]
