# Generated by Django 4.2.14 on 2024-08-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0003_constructionsworks_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionsworks',
            options={'verbose_name': 'Вид Работы'},
        ),
    ]
